<?php
$page = 'toplist';
$pagename = 'Top List';
require_once 'header.php';
?>

<div class="toplist-container">
    <?php

    $query = "SELECT count(*), cid, c.pic, c.name, ROUND((SUM(outcome)/count(*))*100, 0) as 'winrate', ROUND(AVG(kills), 1) as 'kills', ROUND(AVG(deaths), 1) as 'deaths', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(cs), 1) as 'cs', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(damage), 1) as 'damage', ROUND(AVG(gold), 1) as 'gold', ROUND(AVG(cs/(length/60)), 2) as 'csm', ROUND(AVG(damage/(length/60)), 2) as 'dmgm', ROUND(AVG(gold/(length/60)), 2) as 'goldm'
    FROM
    ((SELECT json_extract(data, '$.participantIdentities[0].player.summonerId') as 'pid', json_extract(data, '$.participants[0].championId') as 'cid', (CASE WHEN json_extract(data, '$.participants[0].stats.winner')=true then 1 else 0 end) as 'outcome', json_extract(data, '$.participants[0].stats.kills') as 'kills', json_extract(data, '$.participants[0].stats.deaths') as 'deaths', json_extract(data, '$.participants[0].stats.assists') as 'assists', (json_extract(data, '$.participants[0].stats.minionsKilled')+json_extract(data, '$.participants[0].stats.neutralMinionsKilled')) as 'cs', json_extract(data, '$.participants[0].stats.totalDamageDealtToChampions') as 'damage', json_extract(data, '$.matchDuration') as 'length', json_extract(data, '$.participants[0].stats.goldEarned') as 'gold' FROM matches_".$region.")
    UNION ALL (SELECT json_extract(data, '$.participantIdentities[1].player.summonerId'), json_extract(data, '$.participants[1].championId'), (CASE WHEN json_extract(data, '$.participants[1].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[1].stats.kills'), json_extract(data, '$.participants[1].stats.deaths'), json_extract(data, '$.participants[1].stats.assists'), (json_extract(data, '$.participants[1].stats.minionsKilled')+json_extract(data, '$.participants[1].stats.neutralMinionsKilled')), json_extract(data, '$.participants[1].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[1].stats.goldEarned') FROM matches_".$region.")
    UNION ALL (SELECT json_extract(data, '$.participantIdentities[2].player.summonerId'), json_extract(data, '$.participants[2].championId'), (CASE WHEN json_extract(data, '$.participants[2].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[2].stats.kills'), json_extract(data, '$.participants[2].stats.deaths'), json_extract(data, '$.participants[2].stats.assists'), (json_extract(data, '$.participants[2].stats.minionsKilled')+json_extract(data, '$.participants[2].stats.neutralMinionsKilled')), json_extract(data, '$.participants[2].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[2].stats.goldEarned') FROM matches_".$region.")
    UNION ALL (SELECT json_extract(data, '$.participantIdentities[3].player.summonerId'), json_extract(data, '$.participants[3].championId'), (CASE WHEN json_extract(data, '$.participants[3].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[3].stats.kills'), json_extract(data, '$.participants[3].stats.deaths'), json_extract(data, '$.participants[3].stats.assists'), (json_extract(data, '$.participants[3].stats.minionsKilled')+json_extract(data, '$.participants[3].stats.neutralMinionsKilled')), json_extract(data, '$.participants[3].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[3].stats.goldEarned') FROM matches_".$region.")
    UNION ALL (SELECT json_extract(data, '$.participantIdentities[4].player.summonerId'), json_extract(data, '$.participants[4].championId'), (CASE WHEN json_extract(data, '$.participants[4].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[4].stats.kills'), json_extract(data, '$.participants[4].stats.deaths'), json_extract(data, '$.participants[4].stats.assists'), (json_extract(data, '$.participants[4].stats.minionsKilled')+json_extract(data, '$.participants[4].stats.neutralMinionsKilled')), json_extract(data, '$.participants[4].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[4].stats.goldEarned') FROM matches_".$region.")
    UNION ALL (SELECT json_extract(data, '$.participantIdentities[5].player.summonerId'), json_extract(data, '$.participants[5].championId'), (CASE WHEN json_extract(data, '$.participants[5].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[5].stats.kills'), json_extract(data, '$.participants[5].stats.deaths'), json_extract(data, '$.participants[5].stats.assists'), (json_extract(data, '$.participants[5].stats.minionsKilled')+json_extract(data, '$.participants[5].stats.neutralMinionsKilled')), json_extract(data, '$.participants[5].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[5].stats.goldEarned') FROM matches_".$region.")
    UNION ALL (SELECT json_extract(data, '$.participantIdentities[6].player.summonerId'), json_extract(data, '$.participants[6].championId'), (CASE WHEN json_extract(data, '$.participants[6].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[6].stats.kills'), json_extract(data, '$.participants[6].stats.deaths'), json_extract(data, '$.participants[6].stats.assists'), (json_extract(data, '$.participants[6].stats.minionsKilled')+json_extract(data, '$.participants[6].stats.neutralMinionsKilled')), json_extract(data, '$.participants[6].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[6].stats.goldEarned') FROM matches_".$region.")
    UNION ALL (SELECT json_extract(data, '$.participantIdentities[7].player.summonerId'), json_extract(data, '$.participants[7].championId'), (CASE WHEN json_extract(data, '$.participants[7].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[7].stats.kills'), json_extract(data, '$.participants[7].stats.deaths'), json_extract(data, '$.participants[7].stats.assists'), (json_extract(data, '$.participants[7].stats.minionsKilled')+json_extract(data, '$.participants[7].stats.neutralMinionsKilled')), json_extract(data, '$.participants[7].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[7].stats.goldEarned') FROM matches_".$region.")
    UNION ALL (SELECT json_extract(data, '$.participantIdentities[8].player.summonerId'), json_extract(data, '$.participants[8].championId'), (CASE WHEN json_extract(data, '$.participants[8].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[8].stats.kills'), json_extract(data, '$.participants[8].stats.deaths'), json_extract(data, '$.participants[8].stats.assists'), (json_extract(data, '$.participants[8].stats.minionsKilled')+json_extract(data, '$.participants[8].stats.neutralMinionsKilled')), json_extract(data, '$.participants[8].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[8].stats.goldEarned') FROM matches_".$region.")
    UNION ALL (SELECT json_extract(data, '$.participantIdentities[9].player.summonerId'), json_extract(data, '$.participants[9].championId'), (CASE WHEN json_extract(data, '$.participants[9].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[9].stats.kills'), json_extract(data, '$.participants[9].stats.deaths'), json_extract(data, '$.participants[9].stats.assists'), (json_extract(data, '$.participants[9].stats.minionsKilled')+json_extract(data, '$.participants[9].stats.neutralMinionsKilled')), json_extract(data, '$.participants[9].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[9].stats.goldEarned') FROM matches_".$region.")) t
    LEFT JOIN champions c ON cid=c.id
    GROUP BY cid, 3, 4
    ORDER BY 1 DESC LIMIT 20";
    $result = $conn->prepare($query);
    $result->execute();
    $table = $result->fetchAll();

    echo '<div class="toplist-col">';

    echo '<div class="sideinfo-box">';
    echo '<div class="sideinfo-title">';
    echo 'Champions:';
    echo '</div>';

    foreach($table as $row) {
        echo '<div class="sideinfo-row">';
        echo '<div class="sideinfo-row-played">'.$row[0].' Played - '.$row['winrate'].'% Winrate</div>';
        echo '<div class="sideinfo-row-pic">'.getChampionIMG($row['pic'], $row['name'], '6.6.1', 40, 40).'</div>';
    //    echo '<div class="sideinfo-row-winrate">'.$row['winrate'].'%'.'</div>';
        echo '<div class="sideinfo-row-kda">'.$row['kills'].'/';
        echo $row['deaths'].'/';
        echo $row['assists'];
        echo '<div>'.round(($row['kills']+$row['assists'])/$row['deaths'],1).':1 KDA'.'</div>';
        echo '</div>';
        echo '<div class="sideinfo-row-stats">';
        echo '<div class="sideinfo-row-damage">'.'Damage: '.$row['damage'].' ('.$row['dmgm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-gold">'.'Gold: '.$row['gold'].' ('.$row['goldm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-cs">'.'CS: '.$row['cs'].' ('.$row['csm'].'/min)'.'</div>';
        echo '</div>';
        echo '</div>';
    }
    echo '</div>';
    echo '</div>';

    $query = "SELECT count(*), cid, c.pic, c.name, getCorrectLane(lane, role) as 'correctlane', ROUND((SUM(outcome)/count(*))*100, 0) as 'winrate', ROUND(AVG(kills), 1) as 'kills', ROUND(AVG(deaths), 1) as 'deaths', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(cs), 1) as 'cs', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(damage), 1) as 'damage', ROUND(AVG(gold), 1) as 'gold', ROUND(AVG(cs/(length/60)), 2) as 'csm', ROUND(AVG(damage/(length/60)), 2) as 'dmgm', ROUND(AVG(gold/(length/60)), 2) as 'goldm'
FROM
((SELECT json_extract(data, '$.participantIdentities[0].player.summonerId') as 'pid', json_extract(data, '$.participants[0].championId') as 'cid', json_extract(data, '$.participants[0].timeline.lane') as 'lane', json_extract(data, '$.participants[0].timeline.role') as 'role', (CASE WHEN json_extract(data, '$.participants[0].stats.winner')=true then 1 else 0 end) as 'outcome', json_extract(data, '$.participants[0].stats.kills') as 'kills', json_extract(data, '$.participants[0].stats.deaths') as 'deaths', json_extract(data, '$.participants[0].stats.assists') as 'assists', (json_extract(data, '$.participants[0].stats.minionsKilled')+json_extract(data, '$.participants[0].stats.neutralMinionsKilled')) as 'cs', json_extract(data, '$.participants[0].stats.totalDamageDealtToChampions') as 'damage', json_extract(data, '$.matchDuration') as 'length', json_extract(data, '$.participants[0].stats.goldEarned') as 'gold' FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[1].player.summonerId'), json_extract(data, '$.participants[1].championId'), json_extract(data, '$.participants[1].timeline.lane'), json_extract(data, '$.participants[1].timeline.role'), (CASE WHEN json_extract(data, '$.participants[1].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[1].stats.kills'), json_extract(data, '$.participants[1].stats.deaths'), json_extract(data, '$.participants[1].stats.assists'), (json_extract(data, '$.participants[1].stats.minionsKilled')+json_extract(data, '$.participants[1].stats.neutralMinionsKilled')), json_extract(data, '$.participants[1].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[1].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[2].player.summonerId'), json_extract(data, '$.participants[2].championId'), json_extract(data, '$.participants[2].timeline.lane'), json_extract(data, '$.participants[2].timeline.role'), (CASE WHEN json_extract(data, '$.participants[2].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[2].stats.kills'), json_extract(data, '$.participants[2].stats.deaths'), json_extract(data, '$.participants[2].stats.assists'), (json_extract(data, '$.participants[2].stats.minionsKilled')+json_extract(data, '$.participants[2].stats.neutralMinionsKilled')), json_extract(data, '$.participants[2].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[2].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[3].player.summonerId'), json_extract(data, '$.participants[3].championId'), json_extract(data, '$.participants[3].timeline.lane'), json_extract(data, '$.participants[3].timeline.role'), (CASE WHEN json_extract(data, '$.participants[3].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[3].stats.kills'), json_extract(data, '$.participants[3].stats.deaths'), json_extract(data, '$.participants[3].stats.assists'), (json_extract(data, '$.participants[3].stats.minionsKilled')+json_extract(data, '$.participants[3].stats.neutralMinionsKilled')), json_extract(data, '$.participants[3].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[3].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[4].player.summonerId'), json_extract(data, '$.participants[4].championId'), json_extract(data, '$.participants[4].timeline.lane'), json_extract(data, '$.participants[4].timeline.role'), (CASE WHEN json_extract(data, '$.participants[4].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[4].stats.kills'), json_extract(data, '$.participants[4].stats.deaths'), json_extract(data, '$.participants[4].stats.assists'), (json_extract(data, '$.participants[4].stats.minionsKilled')+json_extract(data, '$.participants[4].stats.neutralMinionsKilled')), json_extract(data, '$.participants[4].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[4].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[5].player.summonerId'), json_extract(data, '$.participants[5].championId'), json_extract(data, '$.participants[5].timeline.lane'), json_extract(data, '$.participants[5].timeline.role'), (CASE WHEN json_extract(data, '$.participants[5].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[5].stats.kills'), json_extract(data, '$.participants[5].stats.deaths'), json_extract(data, '$.participants[5].stats.assists'), (json_extract(data, '$.participants[5].stats.minionsKilled')+json_extract(data, '$.participants[5].stats.neutralMinionsKilled')), json_extract(data, '$.participants[5].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[5].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[6].player.summonerId'), json_extract(data, '$.participants[6].championId'), json_extract(data, '$.participants[6].timeline.lane'), json_extract(data, '$.participants[6].timeline.role'), (CASE WHEN json_extract(data, '$.participants[6].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[6].stats.kills'), json_extract(data, '$.participants[6].stats.deaths'), json_extract(data, '$.participants[6].stats.assists'), (json_extract(data, '$.participants[6].stats.minionsKilled')+json_extract(data, '$.participants[6].stats.neutralMinionsKilled')), json_extract(data, '$.participants[6].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[6].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[7].player.summonerId'), json_extract(data, '$.participants[7].championId'), json_extract(data, '$.participants[7].timeline.lane'), json_extract(data, '$.participants[7].timeline.role'), (CASE WHEN json_extract(data, '$.participants[7].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[7].stats.kills'), json_extract(data, '$.participants[7].stats.deaths'), json_extract(data, '$.participants[7].stats.assists'), (json_extract(data, '$.participants[7].stats.minionsKilled')+json_extract(data, '$.participants[7].stats.neutralMinionsKilled')), json_extract(data, '$.participants[7].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[7].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[8].player.summonerId'), json_extract(data, '$.participants[8].championId'), json_extract(data, '$.participants[8].timeline.lane'), json_extract(data, '$.participants[8].timeline.role'), (CASE WHEN json_extract(data, '$.participants[8].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[8].stats.kills'), json_extract(data, '$.participants[8].stats.deaths'), json_extract(data, '$.participants[8].stats.assists'), (json_extract(data, '$.participants[8].stats.minionsKilled')+json_extract(data, '$.participants[8].stats.neutralMinionsKilled')), json_extract(data, '$.participants[8].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[8].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[9].player.summonerId'), json_extract(data, '$.participants[9].championId'), json_extract(data, '$.participants[9].timeline.lane'), json_extract(data, '$.participants[9].timeline.role'), (CASE WHEN json_extract(data, '$.participants[9].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[9].stats.kills'), json_extract(data, '$.participants[9].stats.deaths'), json_extract(data, '$.participants[9].stats.assists'), (json_extract(data, '$.participants[9].stats.minionsKilled')+json_extract(data, '$.participants[9].stats.neutralMinionsKilled')), json_extract(data, '$.participants[9].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[9].stats.goldEarned') FROM matches_".$region.")) t
LEFT JOIN champions c ON cid=c.id
GROUP BY cid, 3,4,5
HAVING correctlane='Top'
ORDER BY 1 DESC LIMIT 20";
    $result = $conn->prepare($query);
    $result->execute();
    $table = $result->fetchAll();

    echo '<div class="toplist-col">';

    echo '<div class="sideinfo-box">';
    echo '<div class="sideinfo-title">';
    echo 'Top-Laners:';
    echo '</div>';

    foreach($table as $row) {
        echo '<div class="sideinfo-row">';
        echo '<div class="sideinfo-row-played">'.$row[0].' Played - '.$row['winrate'].'% Winrate</div>';
        echo '<div class="sideinfo-row-pic">'.getChampionIMG($row['pic'], $row['name'], '6.6.1', 40, 40).'</div>';
        echo '<div class="sideinfo-row-kda">'.$row['kills'].'/';
        echo $row['deaths'].'/';
        echo $row['assists'];
        echo '<div>'.round(($row['kills']+$row['assists'])/$row['deaths'],1).':1 KDA'.'</div>';
        echo '</div>';
        echo '<div class="sideinfo-row-stats">';
        echo '<div class="sideinfo-row-damage">'.'Damage: '.$row['damage'].' ('.$row['dmgm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-gold">'.'Gold: '.$row['gold'].' ('.$row['goldm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-cs">'.'CS: '.$row['cs'].' ('.$row['csm'].'/min)'.'</div>';
        echo '</div>';
        echo '</div>';
    }
    echo '</div>';
    echo '</div>';

    $query = "SELECT count(*), cid, c.pic, c.name, getCorrectLane(lane, role) as 'correctlane', ROUND((SUM(outcome)/count(*))*100, 0) as 'winrate', ROUND(AVG(kills), 1) as 'kills', ROUND(AVG(deaths), 1) as 'deaths', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(cs), 1) as 'cs', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(damage), 1) as 'damage', ROUND(AVG(gold), 1) as 'gold', ROUND(AVG(cs/(length/60)), 2) as 'csm', ROUND(AVG(damage/(length/60)), 2) as 'dmgm', ROUND(AVG(gold/(length/60)), 2) as 'goldm'
FROM
((SELECT json_extract(data, '$.participantIdentities[0].player.summonerId') as 'pid', json_extract(data, '$.participants[0].championId') as 'cid', json_extract(data, '$.participants[0].timeline.lane') as 'lane', json_extract(data, '$.participants[0].timeline.role') as 'role', (CASE WHEN json_extract(data, '$.participants[0].stats.winner')=true then 1 else 0 end) as 'outcome', json_extract(data, '$.participants[0].stats.kills') as 'kills', json_extract(data, '$.participants[0].stats.deaths') as 'deaths', json_extract(data, '$.participants[0].stats.assists') as 'assists', (json_extract(data, '$.participants[0].stats.minionsKilled')+json_extract(data, '$.participants[0].stats.neutralMinionsKilled')) as 'cs', json_extract(data, '$.participants[0].stats.totalDamageDealtToChampions') as 'damage', json_extract(data, '$.matchDuration') as 'length', json_extract(data, '$.participants[0].stats.goldEarned') as 'gold' FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[1].player.summonerId'), json_extract(data, '$.participants[1].championId'), json_extract(data, '$.participants[1].timeline.lane'), json_extract(data, '$.participants[1].timeline.role'), (CASE WHEN json_extract(data, '$.participants[1].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[1].stats.kills'), json_extract(data, '$.participants[1].stats.deaths'), json_extract(data, '$.participants[1].stats.assists'), (json_extract(data, '$.participants[1].stats.minionsKilled')+json_extract(data, '$.participants[1].stats.neutralMinionsKilled')), json_extract(data, '$.participants[1].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[1].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[2].player.summonerId'), json_extract(data, '$.participants[2].championId'), json_extract(data, '$.participants[2].timeline.lane'), json_extract(data, '$.participants[2].timeline.role'), (CASE WHEN json_extract(data, '$.participants[2].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[2].stats.kills'), json_extract(data, '$.participants[2].stats.deaths'), json_extract(data, '$.participants[2].stats.assists'), (json_extract(data, '$.participants[2].stats.minionsKilled')+json_extract(data, '$.participants[2].stats.neutralMinionsKilled')), json_extract(data, '$.participants[2].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[2].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[3].player.summonerId'), json_extract(data, '$.participants[3].championId'), json_extract(data, '$.participants[3].timeline.lane'), json_extract(data, '$.participants[3].timeline.role'), (CASE WHEN json_extract(data, '$.participants[3].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[3].stats.kills'), json_extract(data, '$.participants[3].stats.deaths'), json_extract(data, '$.participants[3].stats.assists'), (json_extract(data, '$.participants[3].stats.minionsKilled')+json_extract(data, '$.participants[3].stats.neutralMinionsKilled')), json_extract(data, '$.participants[3].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[3].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[4].player.summonerId'), json_extract(data, '$.participants[4].championId'), json_extract(data, '$.participants[4].timeline.lane'), json_extract(data, '$.participants[4].timeline.role'), (CASE WHEN json_extract(data, '$.participants[4].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[4].stats.kills'), json_extract(data, '$.participants[4].stats.deaths'), json_extract(data, '$.participants[4].stats.assists'), (json_extract(data, '$.participants[4].stats.minionsKilled')+json_extract(data, '$.participants[4].stats.neutralMinionsKilled')), json_extract(data, '$.participants[4].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[4].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[5].player.summonerId'), json_extract(data, '$.participants[5].championId'), json_extract(data, '$.participants[5].timeline.lane'), json_extract(data, '$.participants[5].timeline.role'), (CASE WHEN json_extract(data, '$.participants[5].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[5].stats.kills'), json_extract(data, '$.participants[5].stats.deaths'), json_extract(data, '$.participants[5].stats.assists'), (json_extract(data, '$.participants[5].stats.minionsKilled')+json_extract(data, '$.participants[5].stats.neutralMinionsKilled')), json_extract(data, '$.participants[5].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[5].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[6].player.summonerId'), json_extract(data, '$.participants[6].championId'), json_extract(data, '$.participants[6].timeline.lane'), json_extract(data, '$.participants[6].timeline.role'), (CASE WHEN json_extract(data, '$.participants[6].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[6].stats.kills'), json_extract(data, '$.participants[6].stats.deaths'), json_extract(data, '$.participants[6].stats.assists'), (json_extract(data, '$.participants[6].stats.minionsKilled')+json_extract(data, '$.participants[6].stats.neutralMinionsKilled')), json_extract(data, '$.participants[6].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[6].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[7].player.summonerId'), json_extract(data, '$.participants[7].championId'), json_extract(data, '$.participants[7].timeline.lane'), json_extract(data, '$.participants[7].timeline.role'), (CASE WHEN json_extract(data, '$.participants[7].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[7].stats.kills'), json_extract(data, '$.participants[7].stats.deaths'), json_extract(data, '$.participants[7].stats.assists'), (json_extract(data, '$.participants[7].stats.minionsKilled')+json_extract(data, '$.participants[7].stats.neutralMinionsKilled')), json_extract(data, '$.participants[7].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[7].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[8].player.summonerId'), json_extract(data, '$.participants[8].championId'), json_extract(data, '$.participants[8].timeline.lane'), json_extract(data, '$.participants[8].timeline.role'), (CASE WHEN json_extract(data, '$.participants[8].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[8].stats.kills'), json_extract(data, '$.participants[8].stats.deaths'), json_extract(data, '$.participants[8].stats.assists'), (json_extract(data, '$.participants[8].stats.minionsKilled')+json_extract(data, '$.participants[8].stats.neutralMinionsKilled')), json_extract(data, '$.participants[8].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[8].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[9].player.summonerId'), json_extract(data, '$.participants[9].championId'), json_extract(data, '$.participants[9].timeline.lane'), json_extract(data, '$.participants[9].timeline.role'), (CASE WHEN json_extract(data, '$.participants[9].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[9].stats.kills'), json_extract(data, '$.participants[9].stats.deaths'), json_extract(data, '$.participants[9].stats.assists'), (json_extract(data, '$.participants[9].stats.minionsKilled')+json_extract(data, '$.participants[9].stats.neutralMinionsKilled')), json_extract(data, '$.participants[9].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[9].stats.goldEarned') FROM matches_".$region.")) t
LEFT JOIN champions c ON cid=c.id
GROUP BY cid, 3,4,5
HAVING correctlane='Jungle'
ORDER BY 1 DESC LIMIT 20";
    $result = $conn->prepare($query);
    $result->execute();
    $table = $result->fetchAll();

    echo '<div class="toplist-col">';

    echo '<div class="sideinfo-box">';
    echo '<div class="sideinfo-title">';
    echo 'Junglers:';
    echo '</div>';

    foreach($table as $row) {
        echo '<div class="sideinfo-row">';
        echo '<div class="sideinfo-row-played">'.$row[0].' Played - '.$row['winrate'].'% Winrate</div>';
        echo '<div class="sideinfo-row-pic">'.getChampionIMG($row['pic'], $row['name'], '6.6.1', 40, 40).'</div>';
        echo '<div class="sideinfo-row-kda">'.$row['kills'].'/';
        echo $row['deaths'].'/';
        echo $row['assists'];
        echo '<div>'.round(($row['kills']+$row['assists'])/$row['deaths'],1).':1 KDA'.'</div>';
        echo '</div>';
        echo '<div class="sideinfo-row-stats">';
        echo '<div class="sideinfo-row-damage">'.'Damage: '.$row['damage'].' ('.$row['dmgm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-gold">'.'Gold: '.$row['gold'].' ('.$row['goldm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-cs">'.'CS: '.$row['cs'].' ('.$row['csm'].'/min)'.'</div>';
        echo '</div>';
        echo '</div>';
    }
    echo '</div>';
    echo '</div>';

    $query = "SELECT count(*), cid, c.pic, c.name, getCorrectLane(lane, role) as 'correctlane', ROUND((SUM(outcome)/count(*))*100, 0) as 'winrate', ROUND(AVG(kills), 1) as 'kills', ROUND(AVG(deaths), 1) as 'deaths', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(cs), 1) as 'cs', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(damage), 1) as 'damage', ROUND(AVG(gold), 1) as 'gold', ROUND(AVG(cs/(length/60)), 2) as 'csm', ROUND(AVG(damage/(length/60)), 2) as 'dmgm', ROUND(AVG(gold/(length/60)), 2) as 'goldm'
FROM
((SELECT json_extract(data, '$.participantIdentities[0].player.summonerId') as 'pid', json_extract(data, '$.participants[0].championId') as 'cid', json_extract(data, '$.participants[0].timeline.lane') as 'lane', json_extract(data, '$.participants[0].timeline.role') as 'role', (CASE WHEN json_extract(data, '$.participants[0].stats.winner')=true then 1 else 0 end) as 'outcome', json_extract(data, '$.participants[0].stats.kills') as 'kills', json_extract(data, '$.participants[0].stats.deaths') as 'deaths', json_extract(data, '$.participants[0].stats.assists') as 'assists', (json_extract(data, '$.participants[0].stats.minionsKilled')+json_extract(data, '$.participants[0].stats.neutralMinionsKilled')) as 'cs', json_extract(data, '$.participants[0].stats.totalDamageDealtToChampions') as 'damage', json_extract(data, '$.matchDuration') as 'length', json_extract(data, '$.participants[0].stats.goldEarned') as 'gold' FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[1].player.summonerId'), json_extract(data, '$.participants[1].championId'), json_extract(data, '$.participants[1].timeline.lane'), json_extract(data, '$.participants[1].timeline.role'), (CASE WHEN json_extract(data, '$.participants[1].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[1].stats.kills'), json_extract(data, '$.participants[1].stats.deaths'), json_extract(data, '$.participants[1].stats.assists'), (json_extract(data, '$.participants[1].stats.minionsKilled')+json_extract(data, '$.participants[1].stats.neutralMinionsKilled')), json_extract(data, '$.participants[1].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[1].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[2].player.summonerId'), json_extract(data, '$.participants[2].championId'), json_extract(data, '$.participants[2].timeline.lane'), json_extract(data, '$.participants[2].timeline.role'), (CASE WHEN json_extract(data, '$.participants[2].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[2].stats.kills'), json_extract(data, '$.participants[2].stats.deaths'), json_extract(data, '$.participants[2].stats.assists'), (json_extract(data, '$.participants[2].stats.minionsKilled')+json_extract(data, '$.participants[2].stats.neutralMinionsKilled')), json_extract(data, '$.participants[2].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[2].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[3].player.summonerId'), json_extract(data, '$.participants[3].championId'), json_extract(data, '$.participants[3].timeline.lane'), json_extract(data, '$.participants[3].timeline.role'), (CASE WHEN json_extract(data, '$.participants[3].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[3].stats.kills'), json_extract(data, '$.participants[3].stats.deaths'), json_extract(data, '$.participants[3].stats.assists'), (json_extract(data, '$.participants[3].stats.minionsKilled')+json_extract(data, '$.participants[3].stats.neutralMinionsKilled')), json_extract(data, '$.participants[3].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[3].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[4].player.summonerId'), json_extract(data, '$.participants[4].championId'), json_extract(data, '$.participants[4].timeline.lane'), json_extract(data, '$.participants[4].timeline.role'), (CASE WHEN json_extract(data, '$.participants[4].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[4].stats.kills'), json_extract(data, '$.participants[4].stats.deaths'), json_extract(data, '$.participants[4].stats.assists'), (json_extract(data, '$.participants[4].stats.minionsKilled')+json_extract(data, '$.participants[4].stats.neutralMinionsKilled')), json_extract(data, '$.participants[4].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[4].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[5].player.summonerId'), json_extract(data, '$.participants[5].championId'), json_extract(data, '$.participants[5].timeline.lane'), json_extract(data, '$.participants[5].timeline.role'), (CASE WHEN json_extract(data, '$.participants[5].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[5].stats.kills'), json_extract(data, '$.participants[5].stats.deaths'), json_extract(data, '$.participants[5].stats.assists'), (json_extract(data, '$.participants[5].stats.minionsKilled')+json_extract(data, '$.participants[5].stats.neutralMinionsKilled')), json_extract(data, '$.participants[5].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[5].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[6].player.summonerId'), json_extract(data, '$.participants[6].championId'), json_extract(data, '$.participants[6].timeline.lane'), json_extract(data, '$.participants[6].timeline.role'), (CASE WHEN json_extract(data, '$.participants[6].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[6].stats.kills'), json_extract(data, '$.participants[6].stats.deaths'), json_extract(data, '$.participants[6].stats.assists'), (json_extract(data, '$.participants[6].stats.minionsKilled')+json_extract(data, '$.participants[6].stats.neutralMinionsKilled')), json_extract(data, '$.participants[6].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[6].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[7].player.summonerId'), json_extract(data, '$.participants[7].championId'), json_extract(data, '$.participants[7].timeline.lane'), json_extract(data, '$.participants[7].timeline.role'), (CASE WHEN json_extract(data, '$.participants[7].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[7].stats.kills'), json_extract(data, '$.participants[7].stats.deaths'), json_extract(data, '$.participants[7].stats.assists'), (json_extract(data, '$.participants[7].stats.minionsKilled')+json_extract(data, '$.participants[7].stats.neutralMinionsKilled')), json_extract(data, '$.participants[7].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[7].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[8].player.summonerId'), json_extract(data, '$.participants[8].championId'), json_extract(data, '$.participants[8].timeline.lane'), json_extract(data, '$.participants[8].timeline.role'), (CASE WHEN json_extract(data, '$.participants[8].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[8].stats.kills'), json_extract(data, '$.participants[8].stats.deaths'), json_extract(data, '$.participants[8].stats.assists'), (json_extract(data, '$.participants[8].stats.minionsKilled')+json_extract(data, '$.participants[8].stats.neutralMinionsKilled')), json_extract(data, '$.participants[8].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[8].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[9].player.summonerId'), json_extract(data, '$.participants[9].championId'), json_extract(data, '$.participants[9].timeline.lane'), json_extract(data, '$.participants[9].timeline.role'), (CASE WHEN json_extract(data, '$.participants[9].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[9].stats.kills'), json_extract(data, '$.participants[9].stats.deaths'), json_extract(data, '$.participants[9].stats.assists'), (json_extract(data, '$.participants[9].stats.minionsKilled')+json_extract(data, '$.participants[9].stats.neutralMinionsKilled')), json_extract(data, '$.participants[9].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[9].stats.goldEarned') FROM matches_".$region.")) t
LEFT JOIN champions c ON cid=c.id
GROUP BY cid, 3,4,5
HAVING correctlane='Mid'
ORDER BY 1 DESC LIMIT 20";
    $result = $conn->prepare($query);
    $result->execute();
    $table = $result->fetchAll();

    echo '<div class="toplist-col">';

    echo '<div class="sideinfo-box">';
    echo '<div class="sideinfo-title">';
    echo 'Mid-Laners:';
    echo '</div>';

    foreach($table as $row) {
        echo '<div class="sideinfo-row">';
        echo '<div class="sideinfo-row-played">'.$row[0].' Played - '.$row['winrate'].'% Winrate</div>';
        echo '<div class="sideinfo-row-pic">'.getChampionIMG($row['pic'], $row['name'], '6.6.1', 40, 40).'</div>';
        echo '<div class="sideinfo-row-kda">'.$row['kills'].'/';
        echo $row['deaths'].'/';
        echo $row['assists'];
        echo '<div>'.round(($row['kills']+$row['assists'])/$row['deaths'],1).':1 KDA'.'</div>';
        echo '</div>';
        echo '<div class="sideinfo-row-stats">';
        echo '<div class="sideinfo-row-damage">'.'Damage: '.$row['damage'].' ('.$row['dmgm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-gold">'.'Gold: '.$row['gold'].' ('.$row['goldm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-cs">'.'CS: '.$row['cs'].' ('.$row['csm'].'/min)'.'</div>';
        echo '</div>';
        echo '</div>';
    }
    echo '</div>';
    echo '</div>';

    $query = "SELECT count(*), cid, c.pic, c.name, getCorrectLane(lane, role) as 'correctlane', ROUND((SUM(outcome)/count(*))*100, 0) as 'winrate', ROUND(AVG(kills), 1) as 'kills', ROUND(AVG(deaths), 1) as 'deaths', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(cs), 1) as 'cs', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(damage), 1) as 'damage', ROUND(AVG(gold), 1) as 'gold', ROUND(AVG(cs/(length/60)), 2) as 'csm', ROUND(AVG(damage/(length/60)), 2) as 'dmgm', ROUND(AVG(gold/(length/60)), 2) as 'goldm'
FROM
((SELECT json_extract(data, '$.participantIdentities[0].player.summonerId') as 'pid', json_extract(data, '$.participants[0].championId') as 'cid', json_extract(data, '$.participants[0].timeline.lane') as 'lane', json_extract(data, '$.participants[0].timeline.role') as 'role', (CASE WHEN json_extract(data, '$.participants[0].stats.winner')=true then 1 else 0 end) as 'outcome', json_extract(data, '$.participants[0].stats.kills') as 'kills', json_extract(data, '$.participants[0].stats.deaths') as 'deaths', json_extract(data, '$.participants[0].stats.assists') as 'assists', (json_extract(data, '$.participants[0].stats.minionsKilled')+json_extract(data, '$.participants[0].stats.neutralMinionsKilled')) as 'cs', json_extract(data, '$.participants[0].stats.totalDamageDealtToChampions') as 'damage', json_extract(data, '$.matchDuration') as 'length', json_extract(data, '$.participants[0].stats.goldEarned') as 'gold' FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[1].player.summonerId'), json_extract(data, '$.participants[1].championId'), json_extract(data, '$.participants[1].timeline.lane'), json_extract(data, '$.participants[1].timeline.role'), (CASE WHEN json_extract(data, '$.participants[1].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[1].stats.kills'), json_extract(data, '$.participants[1].stats.deaths'), json_extract(data, '$.participants[1].stats.assists'), (json_extract(data, '$.participants[1].stats.minionsKilled')+json_extract(data, '$.participants[1].stats.neutralMinionsKilled')), json_extract(data, '$.participants[1].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[1].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[2].player.summonerId'), json_extract(data, '$.participants[2].championId'), json_extract(data, '$.participants[2].timeline.lane'), json_extract(data, '$.participants[2].timeline.role'), (CASE WHEN json_extract(data, '$.participants[2].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[2].stats.kills'), json_extract(data, '$.participants[2].stats.deaths'), json_extract(data, '$.participants[2].stats.assists'), (json_extract(data, '$.participants[2].stats.minionsKilled')+json_extract(data, '$.participants[2].stats.neutralMinionsKilled')), json_extract(data, '$.participants[2].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[2].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[3].player.summonerId'), json_extract(data, '$.participants[3].championId'), json_extract(data, '$.participants[3].timeline.lane'), json_extract(data, '$.participants[3].timeline.role'), (CASE WHEN json_extract(data, '$.participants[3].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[3].stats.kills'), json_extract(data, '$.participants[3].stats.deaths'), json_extract(data, '$.participants[3].stats.assists'), (json_extract(data, '$.participants[3].stats.minionsKilled')+json_extract(data, '$.participants[3].stats.neutralMinionsKilled')), json_extract(data, '$.participants[3].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[3].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[4].player.summonerId'), json_extract(data, '$.participants[4].championId'), json_extract(data, '$.participants[4].timeline.lane'), json_extract(data, '$.participants[4].timeline.role'), (CASE WHEN json_extract(data, '$.participants[4].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[4].stats.kills'), json_extract(data, '$.participants[4].stats.deaths'), json_extract(data, '$.participants[4].stats.assists'), (json_extract(data, '$.participants[4].stats.minionsKilled')+json_extract(data, '$.participants[4].stats.neutralMinionsKilled')), json_extract(data, '$.participants[4].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[4].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[5].player.summonerId'), json_extract(data, '$.participants[5].championId'), json_extract(data, '$.participants[5].timeline.lane'), json_extract(data, '$.participants[5].timeline.role'), (CASE WHEN json_extract(data, '$.participants[5].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[5].stats.kills'), json_extract(data, '$.participants[5].stats.deaths'), json_extract(data, '$.participants[5].stats.assists'), (json_extract(data, '$.participants[5].stats.minionsKilled')+json_extract(data, '$.participants[5].stats.neutralMinionsKilled')), json_extract(data, '$.participants[5].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[5].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[6].player.summonerId'), json_extract(data, '$.participants[6].championId'), json_extract(data, '$.participants[6].timeline.lane'), json_extract(data, '$.participants[6].timeline.role'), (CASE WHEN json_extract(data, '$.participants[6].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[6].stats.kills'), json_extract(data, '$.participants[6].stats.deaths'), json_extract(data, '$.participants[6].stats.assists'), (json_extract(data, '$.participants[6].stats.minionsKilled')+json_extract(data, '$.participants[6].stats.neutralMinionsKilled')), json_extract(data, '$.participants[6].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[6].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[7].player.summonerId'), json_extract(data, '$.participants[7].championId'), json_extract(data, '$.participants[7].timeline.lane'), json_extract(data, '$.participants[7].timeline.role'), (CASE WHEN json_extract(data, '$.participants[7].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[7].stats.kills'), json_extract(data, '$.participants[7].stats.deaths'), json_extract(data, '$.participants[7].stats.assists'), (json_extract(data, '$.participants[7].stats.minionsKilled')+json_extract(data, '$.participants[7].stats.neutralMinionsKilled')), json_extract(data, '$.participants[7].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[7].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[8].player.summonerId'), json_extract(data, '$.participants[8].championId'), json_extract(data, '$.participants[8].timeline.lane'), json_extract(data, '$.participants[8].timeline.role'), (CASE WHEN json_extract(data, '$.participants[8].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[8].stats.kills'), json_extract(data, '$.participants[8].stats.deaths'), json_extract(data, '$.participants[8].stats.assists'), (json_extract(data, '$.participants[8].stats.minionsKilled')+json_extract(data, '$.participants[8].stats.neutralMinionsKilled')), json_extract(data, '$.participants[8].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[8].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[9].player.summonerId'), json_extract(data, '$.participants[9].championId'), json_extract(data, '$.participants[9].timeline.lane'), json_extract(data, '$.participants[9].timeline.role'), (CASE WHEN json_extract(data, '$.participants[9].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[9].stats.kills'), json_extract(data, '$.participants[9].stats.deaths'), json_extract(data, '$.participants[9].stats.assists'), (json_extract(data, '$.participants[9].stats.minionsKilled')+json_extract(data, '$.participants[9].stats.neutralMinionsKilled')), json_extract(data, '$.participants[9].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[9].stats.goldEarned') FROM matches_".$region.")) t
LEFT JOIN champions c ON cid=c.id
GROUP BY cid, 3,4,5
HAVING correctlane='ADC'
ORDER BY 1 DESC LIMIT 20";
    $result = $conn->prepare($query);
    $result->execute();
    $table = $result->fetchAll();

    echo '<div class="toplist-col">';

    echo '<div class="sideinfo-box">';
    echo '<div class="sideinfo-title">';
    echo 'ADCs:';
    echo '</div>';

    foreach($table as $row) {
        echo '<div class="sideinfo-row">';
        echo '<div class="sideinfo-row-played">'.$row[0].' Played - '.$row['winrate'].'% Winrate</div>';
        echo '<div class="sideinfo-row-pic">'.getChampionIMG($row['pic'], $row['name'], '6.6.1', 40, 40).'</div>';
        echo '<div class="sideinfo-row-kda">'.$row['kills'].'/';
        echo $row['deaths'].'/';
        echo $row['assists'];
        echo '<div>'.round(($row['kills']+$row['assists'])/$row['deaths'],1).':1 KDA'.'</div>';
        echo '</div>';
        echo '<div class="sideinfo-row-stats">';
        echo '<div class="sideinfo-row-damage">'.'Damage: '.$row['damage'].' ('.$row['dmgm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-gold">'.'Gold: '.$row['gold'].' ('.$row['goldm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-cs">'.'CS: '.$row['cs'].' ('.$row['csm'].'/min)'.'</div>';
        echo '</div>';
        echo '</div>';
    }
    echo '</div>';
    echo '</div>';

    $query = "SELECT count(*), cid, c.pic, c.name, getCorrectLane(lane, role) as 'correctlane', ROUND((SUM(outcome)/count(*))*100, 0) as 'winrate', ROUND(AVG(kills), 1) as 'kills', ROUND(AVG(deaths), 1) as 'deaths', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(cs), 1) as 'cs', ROUND(AVG(assists), 1) as 'assists', ROUND(AVG(damage), 1) as 'damage', ROUND(AVG(gold), 1) as 'gold', ROUND(AVG(cs/(length/60)), 2) as 'csm', ROUND(AVG(damage/(length/60)), 2) as 'dmgm', ROUND(AVG(gold/(length/60)), 2) as 'goldm'
FROM
((SELECT json_extract(data, '$.participantIdentities[0].player.summonerId') as 'pid', json_extract(data, '$.participants[0].championId') as 'cid', json_extract(data, '$.participants[0].timeline.lane') as 'lane', json_extract(data, '$.participants[0].timeline.role') as 'role', (CASE WHEN json_extract(data, '$.participants[0].stats.winner')=true then 1 else 0 end) as 'outcome', json_extract(data, '$.participants[0].stats.kills') as 'kills', json_extract(data, '$.participants[0].stats.deaths') as 'deaths', json_extract(data, '$.participants[0].stats.assists') as 'assists', (json_extract(data, '$.participants[0].stats.minionsKilled')+json_extract(data, '$.participants[0].stats.neutralMinionsKilled')) as 'cs', json_extract(data, '$.participants[0].stats.totalDamageDealtToChampions') as 'damage', json_extract(data, '$.matchDuration') as 'length', json_extract(data, '$.participants[0].stats.goldEarned') as 'gold' FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[1].player.summonerId'), json_extract(data, '$.participants[1].championId'), json_extract(data, '$.participants[1].timeline.lane'), json_extract(data, '$.participants[1].timeline.role'), (CASE WHEN json_extract(data, '$.participants[1].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[1].stats.kills'), json_extract(data, '$.participants[1].stats.deaths'), json_extract(data, '$.participants[1].stats.assists'), (json_extract(data, '$.participants[1].stats.minionsKilled')+json_extract(data, '$.participants[1].stats.neutralMinionsKilled')), json_extract(data, '$.participants[1].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[1].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[2].player.summonerId'), json_extract(data, '$.participants[2].championId'), json_extract(data, '$.participants[2].timeline.lane'), json_extract(data, '$.participants[2].timeline.role'), (CASE WHEN json_extract(data, '$.participants[2].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[2].stats.kills'), json_extract(data, '$.participants[2].stats.deaths'), json_extract(data, '$.participants[2].stats.assists'), (json_extract(data, '$.participants[2].stats.minionsKilled')+json_extract(data, '$.participants[2].stats.neutralMinionsKilled')), json_extract(data, '$.participants[2].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[2].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[3].player.summonerId'), json_extract(data, '$.participants[3].championId'), json_extract(data, '$.participants[3].timeline.lane'), json_extract(data, '$.participants[3].timeline.role'), (CASE WHEN json_extract(data, '$.participants[3].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[3].stats.kills'), json_extract(data, '$.participants[3].stats.deaths'), json_extract(data, '$.participants[3].stats.assists'), (json_extract(data, '$.participants[3].stats.minionsKilled')+json_extract(data, '$.participants[3].stats.neutralMinionsKilled')), json_extract(data, '$.participants[3].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[3].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[4].player.summonerId'), json_extract(data, '$.participants[4].championId'), json_extract(data, '$.participants[4].timeline.lane'), json_extract(data, '$.participants[4].timeline.role'), (CASE WHEN json_extract(data, '$.participants[4].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[4].stats.kills'), json_extract(data, '$.participants[4].stats.deaths'), json_extract(data, '$.participants[4].stats.assists'), (json_extract(data, '$.participants[4].stats.minionsKilled')+json_extract(data, '$.participants[4].stats.neutralMinionsKilled')), json_extract(data, '$.participants[4].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[4].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[5].player.summonerId'), json_extract(data, '$.participants[5].championId'), json_extract(data, '$.participants[5].timeline.lane'), json_extract(data, '$.participants[5].timeline.role'), (CASE WHEN json_extract(data, '$.participants[5].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[5].stats.kills'), json_extract(data, '$.participants[5].stats.deaths'), json_extract(data, '$.participants[5].stats.assists'), (json_extract(data, '$.participants[5].stats.minionsKilled')+json_extract(data, '$.participants[5].stats.neutralMinionsKilled')), json_extract(data, '$.participants[5].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[5].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[6].player.summonerId'), json_extract(data, '$.participants[6].championId'), json_extract(data, '$.participants[6].timeline.lane'), json_extract(data, '$.participants[6].timeline.role'), (CASE WHEN json_extract(data, '$.participants[6].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[6].stats.kills'), json_extract(data, '$.participants[6].stats.deaths'), json_extract(data, '$.participants[6].stats.assists'), (json_extract(data, '$.participants[6].stats.minionsKilled')+json_extract(data, '$.participants[6].stats.neutralMinionsKilled')), json_extract(data, '$.participants[6].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[6].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[7].player.summonerId'), json_extract(data, '$.participants[7].championId'), json_extract(data, '$.participants[7].timeline.lane'), json_extract(data, '$.participants[7].timeline.role'), (CASE WHEN json_extract(data, '$.participants[7].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[7].stats.kills'), json_extract(data, '$.participants[7].stats.deaths'), json_extract(data, '$.participants[7].stats.assists'), (json_extract(data, '$.participants[7].stats.minionsKilled')+json_extract(data, '$.participants[7].stats.neutralMinionsKilled')), json_extract(data, '$.participants[7].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[7].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[8].player.summonerId'), json_extract(data, '$.participants[8].championId'), json_extract(data, '$.participants[8].timeline.lane'), json_extract(data, '$.participants[8].timeline.role'), (CASE WHEN json_extract(data, '$.participants[8].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[8].stats.kills'), json_extract(data, '$.participants[8].stats.deaths'), json_extract(data, '$.participants[8].stats.assists'), (json_extract(data, '$.participants[8].stats.minionsKilled')+json_extract(data, '$.participants[8].stats.neutralMinionsKilled')), json_extract(data, '$.participants[8].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[8].stats.goldEarned') FROM matches_".$region.")
UNION ALL (SELECT json_extract(data, '$.participantIdentities[9].player.summonerId'), json_extract(data, '$.participants[9].championId'), json_extract(data, '$.participants[9].timeline.lane'), json_extract(data, '$.participants[9].timeline.role'), (CASE WHEN json_extract(data, '$.participants[9].stats.winner')=true then 1 else 0 end), json_extract(data, '$.participants[9].stats.kills'), json_extract(data, '$.participants[9].stats.deaths'), json_extract(data, '$.participants[9].stats.assists'), (json_extract(data, '$.participants[9].stats.minionsKilled')+json_extract(data, '$.participants[9].stats.neutralMinionsKilled')), json_extract(data, '$.participants[9].stats.totalDamageDealtToChampions'), json_extract(data, '$.matchDuration'), json_extract(data, '$.participants[9].stats.goldEarned') FROM matches_".$region.")) t
LEFT JOIN champions c ON cid=c.id
GROUP BY cid, 3,4,5
HAVING correctlane='Support'
ORDER BY 1 DESC LIMIT 20";
    $result = $conn->prepare($query);
    $result->execute();
    $table = $result->fetchAll();

    echo '<div class="toplist-col">';

    echo '<div class="sideinfo-box">';
    echo '<div class="sideinfo-title">';
    echo 'Supports:';
    echo '</div>';

    foreach($table as $row) {
        echo '<div class="sideinfo-row">';
        echo '<div class="sideinfo-row-played">'.$row[0].' Played - '.$row['winrate'].'% Winrate</div>';
        echo '<div class="sideinfo-row-pic">'.getChampionIMG($row['pic'], $row['name'], '6.6.1', 40, 40).'</div>';
        echo '<div class="sideinfo-row-kda">'.$row['kills'].'/';
        echo $row['deaths'].'/';
        echo $row['assists'];
        echo '<div>'.round(($row['kills']+$row['assists'])/$row['deaths'],1).':1 KDA'.'</div>';
        echo '</div>';
        echo '<div class="sideinfo-row-stats">';
        echo '<div class="sideinfo-row-damage">'.'Damage: '.$row['damage'].' ('.$row['dmgm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-gold">'.'Gold: '.$row['gold'].' ('.$row['goldm'].'/min)'.'</div>';
        echo '<div class="sideinfo-row-cs">'.'CS: '.$row['cs'].' ('.$row['csm'].'/min)'.'</div>';
        echo '</div>';
        echo '</div>';
    }
    echo '</div>';
    echo '</div>';

    ?>

</div>

<?php require_once 'footer.php'; ?>